version: '3.8'

services:
  web:
    build: .
    container_name: jdlab-upload
    ports:
      - "8080:8080"
    volumes:
      - ~/jdlab/uploads:/app/uploads
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-here
    restart: unless-stopped 